import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 11,
    padding: 48,
    color: "#0B0E0D",
    backgroundColor: "#FFFFFF",
  },
  coverPage: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
  },
  coverTitle: {
    fontSize: 28,
    fontFamily: "Helvetica-Bold",
    marginBottom: 8,
    textAlign: "center",
  },
  coverSubtitle: {
    fontSize: 14,
    color: "#5C6360",
    marginBottom: 4,
    textAlign: "center",
  },
  coverDisclaimer: {
    fontSize: 9,
    color: "#9CA3AF",
    textAlign: "center",
    marginTop: 48,
    maxWidth: 400,
  },
  sectionHeader: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    marginTop: 24,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 2,
    borderBottomColor: "#1B3A6B",
    borderBottomStyle: "solid",
  },
  subheader: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    marginTop: 16,
    marginBottom: 4,
  },
  bodyText: {
    fontSize: 11,
    lineHeight: 1.6,
    marginBottom: 8,
    color: "#374151",
  },
  bulletItem: {
    fontSize: 11,
    lineHeight: 1.5,
    marginBottom: 4,
    paddingLeft: 12,
  },
  keyFindingsBox: {
    backgroundColor: "#EEF2F9",
    padding: 16,
    borderRadius: 4,
    marginBottom: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#1B3A6B",
    borderLeftStyle: "solid",
  },
  scoreRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
    borderBottomStyle: "solid",
  },
  scoreName: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    flex: 2,
  },
  scoreValue: {
    fontSize: 10,
    flex: 1,
    textAlign: "right",
  },
  scoreDescriptor: {
    fontSize: 9,
    color: "#6B7280",
    marginTop: 2,
    marginBottom: 6,
  },
  questionNumber: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: "#1B3A6B",
    marginBottom: 2,
  },
  questionPurpose: {
    fontSize: 10,
    color: "#6B7280",
    fontStyle: "italic",
    marginBottom: 12,
  },
  disclaimer: {
    fontSize: 9,
    color: "#9CA3AF",
    fontStyle: "italic",
    marginTop: 8,
    padding: 8,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderStyle: "solid",
  },
  pageNumber: {
    position: "absolute",
    bottom: 24,
    right: 48,
    fontSize: 9,
    color: "#9CA3AF",
  },
});

type ScoreFound = {
  name: string;
  score: number | null;
  percentile: number | null;
  scoreType?: string;
  descriptor: string;
};

type Battery = {
  batteryName: string;
  batteryFullName: string;
  whatItMeasures: string;
  scoresFound: ScoreFound[];
  plainEnglishSummary: string;
};

type Service = {
  serviceName: string;
  why: string;
  typicalFrequency: string;
  priorityLevel: string;
};

type AccommodationCategory = {
  category: string;
  accommodations: { name: string; why: string }[];
};

type Question = { question: string; purpose: string };

type Rights = {
  stateTerminology: string;
  keyRights: string[];
  timelines: string[];
  ieeRight: string;
};

interface BriefData {
  summary?: string;
  scoresExplained?: Battery[];
  services?: Service[];
  accommodations?: AccommodationCategory[];
  questions?: Question[];
  watchFor?: string;
  rights?: Rights | null;
  keyFindings?: string[];
  formalDiagnoses?: string[];
}

interface BriefPDFProps {
  brief: BriefData;
  childName: string;
  generatedDate: string;
}

const PageFooter = () => (
  <Text
    style={styles.pageNumber}
    render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
    fixed
  />
);

export function BriefPDF({ brief, childName, generatedDate }: BriefPDFProps) {
  const scores = brief.scoresExplained ?? [];
  const services = brief.services ?? [];
  const accommodations = brief.accommodations ?? [];
  const questions = brief.questions ?? [];
  const keyFindings = brief.keyFindings ?? [];
  const formalDiagnoses = brief.formalDiagnoses ?? [];

  return (
    <Document>
      {/* Cover */}
      <Page size="A4" style={styles.page}>
        <View style={styles.coverPage}>
          <Text style={styles.coverTitle}>{`${childName}'s\nIEP Meeting Brief`}</Text>
          <Text style={styles.coverSubtitle}>Generated by Clearpath</Text>
          <Text style={styles.coverSubtitle}>{generatedDate}</Text>
          {formalDiagnoses.length > 0 && (
            <View style={{ marginTop: 32, alignItems: "center" }}>
              <Text
                style={{
                  fontSize: 10,
                  color: "#5C6360",
                  marginBottom: 8,
                  textTransform: "uppercase",
                  letterSpacing: 1,
                }}
              >
                Formal Diagnoses
              </Text>
              {formalDiagnoses.map((d, i) => (
                <Text
                  key={i}
                  style={{
                    fontSize: 12,
                    fontFamily: "Helvetica-Bold",
                    color: "#1B3A6B",
                    marginBottom: 4,
                  }}
                >
                  {d}
                </Text>
              ))}
            </View>
          )}
          <Text style={styles.coverDisclaimer}>
            This brief was generated by Clearpath to help you prepare for your
            child&apos;s IEP meeting. It is not legal advice and does not
            replace the guidance of a qualified special education advocate or
            attorney. These recommendations are based on your child&apos;s
            score profile and are intended to support your conversation with
            the IEP team, not to make legal determinations of eligibility.
          </Text>
        </View>
        <PageFooter />
      </Page>

      {/* Key Findings + Summary */}
      <Page size="A4" style={styles.page}>
        {keyFindings.length > 0 && (
          <>
            <Text style={styles.sectionHeader}>Key Findings</Text>
            <View style={styles.keyFindingsBox}>
              {keyFindings.map((finding, i) => (
                <Text key={i} style={styles.bulletItem}>
                  {`• ${finding}`}
                </Text>
              ))}
            </View>
          </>
        )}

        <Text style={styles.sectionHeader}>Section 1: What This Report Is Saying</Text>
        <Text style={styles.bodyText}>{brief.summary ?? ""}</Text>
        <PageFooter />
      </Page>

      {/* Section 2: Scores */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionHeader}>Section 2: Your Child&apos;s Scores Explained</Text>
        {scores.map((battery, i) => (
          <View key={i} style={{ marginBottom: 16 }} wrap={false}>
            <Text style={styles.subheader}>{battery.batteryFullName}</Text>
            <Text style={{ fontSize: 9, color: "#6B7280", marginBottom: 8 }}>
              {battery.whatItMeasures}
            </Text>
            {(battery.scoresFound ?? []).map((score, j) => (
              <View key={j}>
                <View style={styles.scoreRow}>
                  <Text style={styles.scoreName}>{score.name}</Text>
                  <Text style={styles.scoreValue}>
                    {score.score ?? "N/A"}
                    {score.percentile != null ? ` (${score.percentile}th pct)` : ""}
                  </Text>
                </View>
                <Text style={styles.scoreDescriptor}>{score.descriptor}</Text>
              </View>
            ))}
            <Text style={[styles.bodyText, { marginTop: 4 }]}>
              {battery.plainEnglishSummary}
            </Text>
          </View>
        ))}
        <PageFooter />
      </Page>

      {/* Section 3: Services */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionHeader}>Section 3: Services Your Child May Qualify For</Text>
        {services.map((service, i) => (
          <View key={i} style={{ marginBottom: 12 }} wrap={false}>
            <Text style={styles.subheader}>{service.serviceName}</Text>
            <Text style={styles.bodyText}>{service.why}</Text>
            <Text style={{ fontSize: 10, color: "#6B7280" }}>
              Typical frequency: {service.typicalFrequency}
            </Text>
          </View>
        ))}
        <Text style={styles.disclaimer}>
          These recommendations are based on your child&apos;s score profile.
          They are not legal determinations of eligibility. Discuss with your
          IEP team.
        </Text>
        <PageFooter />
      </Page>

      {/* Section 4: Accommodations */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionHeader}>Section 4: Accommodations Worth Requesting</Text>
        {accommodations.map((category, i) => (
          <View key={i} style={{ marginBottom: 12 }}>
            <Text style={styles.subheader}>{category.category}</Text>
            {(category.accommodations ?? []).map((acc, j) => (
              <View key={j} style={{ marginBottom: 8 }} wrap={false}>
                <Text style={{ fontSize: 11, fontFamily: "Helvetica-Bold" }}>
                  {`• ${acc.name}`}
                </Text>
                <Text style={[styles.bodyText, { paddingLeft: 12 }]}>{acc.why}</Text>
              </View>
            ))}
          </View>
        ))}
        <PageFooter />
      </Page>

      {/* Section 5: Questions */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionHeader}>Section 5: Your 10 Questions for the Meeting</Text>
        <Text style={[styles.bodyText, { color: "#6B7280", marginBottom: 12 }]}>
          Bring this page to the meeting. Ask each question and write down the
          district&apos;s answer.
        </Text>
        {questions.map((q, i) => (
          <View key={i} style={{ marginBottom: 16 }} wrap={false}>
            <Text style={styles.questionNumber}>{`${i + 1}. ${q.question}`}</Text>
            <Text style={styles.questionPurpose}>Why this matters: {q.purpose}</Text>
            <View
              style={{
                height: 24,
                borderBottomWidth: 1,
                borderBottomColor: "#E5E7EB",
                borderBottomStyle: "solid",
              }}
            />
          </View>
        ))}
        <PageFooter />
      </Page>

      {/* Sections 6 + 7 */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionHeader}>Section 6: What to Watch For</Text>
        <Text style={styles.bodyText}>{brief.watchFor ?? ""}</Text>

        <Text style={styles.sectionHeader}>Section 7: Know Your Rights</Text>
        {brief.rights && (
          <View>
            <Text style={styles.subheader}>
              Your meeting is called: {brief.rights.stateTerminology}
            </Text>
            <Text style={[styles.subheader, { marginTop: 12 }]}>Your Key Rights</Text>
            {(brief.rights.keyRights ?? []).map((right, i) => (
              <Text key={i} style={styles.bulletItem}>
                {`• ${right}`}
              </Text>
            ))}
            <Text style={[styles.subheader, { marginTop: 12 }]}>Key Timelines</Text>
            {(brief.rights.timelines ?? []).map((timeline, i) => (
              <Text key={i} style={styles.bulletItem}>
                {`• ${timeline}`}
              </Text>
            ))}
            <Text style={[styles.subheader, { marginTop: 12 }]}>
              Your Right to an Independent Evaluation
            </Text>
            <Text style={styles.bodyText}>{brief.rights.ieeRight}</Text>
          </View>
        )}
        <Text style={styles.disclaimer}>
          This brief was generated by Clearpath to help you prepare for your
          child&apos;s IEP meeting. It is not legal advice. For formal legal
          questions, consult a licensed special education attorney or advocate.
        </Text>
        <PageFooter />
      </Page>
    </Document>
  );
}
